[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Handle defeating custom small/big blinds
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "G.GAME.round_resets.blind_states.Big = 'Defeated'"
position = 'after'
match_indent = true
payload = '''
elseif G.GAME.round_resets.blind_type_override and G.GAME.round_resets.blind_type_override[G.GAME.blind_on_deck] then
	G.GAME.round_resets.blind_states[G.GAME.blind_on_deck] = 'Defeated'
'''