local bug_catching_pokedex = {
	caterpie = true,
	metapod = true,
	butterfree = true,
	weedle = true,
	kakuna = true,
	beedrill = true,
	paras = true,
	parasect = true,
	venonat = true,
	venomoth = true,
	scyther = true,
	pinsir = true,
	ledyba = true,
	ledian = true,
	spinarak = true,
	ariados = true,
	yanma = true,
	pineco = true,
	forretress = true,
	scizor = true,
	shuckle = true,
	heracross = true,
	wurmple = true,
	silcoon = true,
	beautifly = true,
	cascoon = true,
	dustox = true,
	surskit = true,
	masquerain = true,
	nincada = true,
	ninjask = true,
	shedinja = true,
	volbeat = true,
	illumise = true,
	anorith = true, -- Not sure if i should put fossil bug here
	armaldo = true,
	kricketot = true,
	kricketune = true,
	burmy = true,
	wormadam = true,
	mothim = true,
	combee = true,
	vespiquen = true,
	skorupi = true,
	yanmega = true,
	sewaddle = true,
	swadloon = true,
	leavanny = true,
	venipede = true,
	whirlipede = true,
	scolipede = true,
	dwebble = true,
	crustle = true,
	karrablast = true,
	escavalier = true,
	joltik = true,
	galvantula = true,
	shelmet = true,
	accelgor = true,
	durant = true,
	larvesta = true,
	volcarona = true,
	genesect = true,
	scatterbug = true,
	spewpa = true,
	vivillon = true,
	grubbin = true,
	charjabug = true,
	vikavolt = true,
	cutiefly = true,
	ribombee = true,
	dewpider = true,
	araquanid = true,
	wimpod = true,
	golisopod = true,
	blipbug = true,
	dottler = true,
	orbeetle = true,
	sizzlipede = true,
	centiskorch = true,
	snom = true,
	frosmoth = true,
	kleavor = true,
	tarountula = true,
	spidops = true,
	nymble = true,
	lokix = true,
	rellor = true,
	rabsca = true,

	-- buzzwole = true, -- Aliens = true, not bug
	-- pheromosa = true,

	-- Paradox bug
	-- slither wing = true
}

local other_poke_jokers = {
	everstone = true,
	tall_grass = true,
	jelly_donut = true,
	mystery_egg = true,
	rival = true,
	pokedex = true,

	-- Pokedex is also given at shop 1
	-- Treasure eatery only in gen 9
}

return {
	bug_contest = bug_catching_pokedex,
	other = other_poke_jokers,
}
